# Generated by Django 5.0.6 on 2024-06-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_scrapeddata_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('profile_pic', models.URLField()),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('followers', models.IntegerField()),
                ('followings', models.IntegerField()),
                ('total_posts', models.IntegerField()),
                ('external_url', models.URLField()),
            ],
        ),
    ]
