# Generated by Django 5.0.6 on 2024-07-03 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_instagramprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('user_id', models.BigIntegerField()),
                ('full_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('follower_count', models.IntegerField()),
                ('following_count', models.IntegerField()),
                ('media_count', models.IntegerField()),
                ('external_url', models.URLField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('user_id', models.BigIntegerField()),
                ('full_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('follower_count', models.IntegerField()),
                ('following_count', models.IntegerField()),
                ('media_count', models.IntegerField()),
                ('external_url', models.URLField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapedData',
        ),
        migrations.RenameField(
            model_name='instagramprofile',
            old_name='followers',
            new_name='followers_count',
        ),
        migrations.RenameField(
            model_name='instagramprofile',
            old_name='followings',
            new_name='followings_count',
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='user_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='follower',
            name='instagram_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to='myapp.instagramprofile'),
        ),
        migrations.AddField(
            model_name='following',
            name='instagram_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='myapp.instagramprofile'),
        ),
    ]
